### PR TITLE
Log EOSID and IP to dblog_steamusers

### PR DESCRIPTION
**Pull request by IgnisAlienus**
Added EOSID and LastIP to dblog_steamusers table and logging to it. Working in PSG so far....

I did manually add the new columns myself prior. Unsure if SquadJS will automatically add the new columns or not. The columns are setup as varchar(255).

### CODE REVIEW

**Comment by IgnisAlienus** [comment]
image

Example of it working. Ignore the columns with "x"s as those are other custom/wip PSG Plugins.

**Comment by IgnisAlienus** [comment]
I should also note that we have a custom plugin for the "PLAYER_CONNECTED" Event that is logging the IPs and EOSIDs onPlayerConnected along with our custom time tracking stuff. Whether or not it will log on wound, death, revive, should be looked at on a server not using a connected event.

**Comment by IgnisAlienus** [comment]
Standby, about to push a fix in a minute, I'm doing the testing without the onplayerconnected

**Comment by IgnisAlienus** [comment]
Okay. I removed updating the EOS ID on each player wound, death, revive and just added an onPlayerConnected.

Lmk what ya think

**Comment by IgnisAlienus** [comment]
Note that to get the id and ip on player connected I had to do info.eosid and info.ip instead of info.player.xxxxx

**Comment by fantinodavide** [comment]
This is being evaluated, not merging now because the table name is `SteamUsers` and would have more than just Steam-related info

**Comment by IgnisAlienus** [comment]
> This is being evaluated, not merging now because the table name is `SteamUsers` and would have more than just Steam-related info

Good point. Easy to rename that table though......well......for us.....not so much the end user going in and make the updates, would be some hand holding in certain cases.

**Comment by fantinodavide** [comment]
If we decide to rename the table, Sequelize should give us all we need to
handle that part via code, but it needs to be discussed

Il mar 26 dic 2023, 20:06 Ignis ***@***.***> ha scritto:

**Pull request closed without merging**
